/** Pedido fictício para preview e impressão de teste da comanda térmica. */
export const ORDER_TICKET_SAMPLE_ORDER = {
  id: '01',
  status: 'novo',
  tipo: 'delivery',
  clienteNome: 'Maria Silva',
  clienteTelefone: '43991929193',
  createdAt: new Date().toISOString(),
  prazo: '19:30',
  enderecoTexto: 'Rua das Flores, 100 - Centro - Londrina',
  observacao: 'Interfone 12. Sem cebola no burger.',
  itens: [
    {
      nome: 'X-Burger Especial',
      qtd: 2,
      precoUnit: 28.9,
      subtotal: 57.8,
      obs: 'Bacon extra, Molho da casa',
    },
    { nome: 'Batata frita M', qtd: 1, precoUnit: 14, subtotal: 14, obs: '' },
    { nome: 'Refrigerante 350ml', qtd: 2, precoUnit: 6, subtotal: 12, obs: 'Coca-Cola' },
  ],
  subtotal: 83.8,
  frete: 8,
  acrescimo: 0,
  desconto: 5,
  cupomCodigo: 'BEMVINDO',
  total: 86.8,
  pagamento: { metodo: 'dinheiro', troco: 100 },
};
